name: github pages

on:
  push:
    branches:
    - hugo

jobs:
  build-deploy:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1        

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --gc --minify --cleanDestinationDir

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public
        publish_branch: main

    - name: Upload Records
      # 使用 Action
      uses: iChochy/Algolia-Upload-Records@main
      # 设置环境变量
      env:
        APPLICATION_ID: ${{secrets.APPLICATION_ID}}
        ADMIN_API_KEY: ${{secrets.ADMIN_API_KEY}}
        INDEX_NAME: ${{secrets.INDEX_NAME}}
        FILE_PATH: ./public/index.json
